apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
spec:
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: argocd, openshift-gitops
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
    - name: DISABLE_DEFAULT_ARGOCD_CONSOLELINK
      value: "true"
  channel: gitops-1.18
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.18.1

#
# EOF