apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: managed-cluster
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - 'managed-cluster'